# This is a basic workflow to help you get started with Actions

name: Central CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  my-build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  
  configuration:
    runs-on: ubuntu-latest
    outputs:
      central-ci-flavour: ${{ steps.central-ci.outputs['central-ci.flavour'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read Config
        uses: nichmor/minimal-read-yaml@v0.0.2
        id: central-ci
        with:
          config: ${{ github.workspace }}/.github/ci-config.yml
      - name: Show config
        run: |
          echo Flavour: ${{ steps.central-ci.outputs['central-ci.flavour'] }}
  
  call-workflow-passing-data:
    needs: configuration
    uses: octodemo/helaili-workflow-playground/.github/workflows/reusable.yml@main
    with:
      flavour: ${{ needs.configuration.outputs.central-ci-flavour }}


      