# This is a basic workflow to help you get started with Actions

name: Central CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  central-build:
    name: Common CI Steps
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  
  configuration:
    name: Configuration
    runs-on: ubuntu-latest
    outputs:
      central-ci-flavour: ${{ steps.central-ci.outputs['central-ci.flavour'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read Config
        uses: nichmor/minimal-read-yaml@v0.0.2
        id: central-ci
        with:
          config: ${{ github.workspace }}/.github/ci-config.yml
      - name: Show config
        run: |
          echo Flavour: ${{ steps.central-ci.outputs['central-ci.flavour'] }}
      # Raise an error if the flavour is not set
      - name: Check config set 
        run: |
          if [ -z "${{ steps.central-ci.outputs['central-ci.flavour'] }}" ]; then
            echo "::error ::Flavour not set in .github/ci-config.yml"
            exit 1
          fi
  
  build:
    name: Central CI Build
    needs: configuration
    uses: actions-blueprints/central-workflows/.github/workflows/reusable.yml@main
    with:
      flavour: ${{ needs.configuration.outputs.central-ci-flavour }}


      