on:
  workflow_call:
    inputs:
      flavour:
        required: true
        type: string

jobs:
  build:
    name: Common Build Steps
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo 'hello world'
  
  build_chocolate:
    name: Chocolate Build
    if: ${{ inputs.flavour == 'chocolate' }}
    uses: actions-blueprints/central-workflows/.github/workflows/reusable-chocolate.yml@main
  
  build_vanilla:
    name: Vanilla Build
    if: ${{ inputs.flavour == 'vanilla' }}
    uses: actions-blueprints/central-workflows/.github/workflows/reusable-vanilla.yml@main
    
