on:
  workflow_call:
    inputs:
      flavour:
        required: true
        type: string

jobs:
  reusable_workflow_job_chocolate:
    if: ${{ inputs.flavour == 'chocolate' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo 'hello world'
  
  reusable_workflow_job_vanilla:
    if: ${{ inputs.flavour == 'vanilla' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo 'hello world'
    
