on:
  workflow_call:
    inputs:
      flavour:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo 'hello world'
  
  reusable_workflow_job_chocolate:
    if: ${{ inputs.flavour == 'chocolate' }}
    uses: octodemo/helaili-workflow-playground/.github/workflows/reusable-chocolate.yml@main
  
  reusable_workflow_job_vanilla:
    if: ${{ inputs.flavour == 'vanilla' }}
    uses: octodemo/helaili-workflow-playground/.github/workflows/reusable-vanilla.yml@main
    
