on:
  workflow_call:
    inputs:
      flavour:
        required: true
        type: string

jobs:
  build:
    name: Common Build Steps
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo 'hello world'
  
  # Raise an error if the flavour is not set
  build-config-check:
    name: Check config set
    runs-on: ubuntu-latest
    steps:
      - name: Check config set 
        run: |
          if [ -z "${{ inputs.flavour }}" ]; then
            echo "::error ::Flavour not set"
            exit 1
          fi
          if [ "${{ inputs.flavour }}" != "chocolate" ] && [ "${{ inputs.flavour }}" != "vanilla" ]; then
            echo "::error ::Unexpected flavour value: ${{ inputs.flavour }}"
            exit 1
          fi
  
  build_chocolate:
    name: Chocolate Build
    if: ${{ inputs.flavour == 'chocolate' }}
    uses: actions-blueprints/central-workflows/.github/workflows/reusable-chocolate.yml@main
  
  build_vanilla:
    name: Vanilla Build
    if: ${{ inputs.flavour == 'vanilla' }}
    uses: actions-blueprints/central-workflows/.github/workflows/reusable-vanilla.yml@main
    
